<a href="https://colab.research.google.com/github/DGluszyk/data-science-bootcamp/blob/main/01_wprowadzenie/01_pandas_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
pd.__version__

'2.2.2'

In [2]:
s = pd.Series([3, 2, 4, 6])
s

0    3
1    2
2    4
3    6
dtype: int64

In [5]:
s = pd.Series(data = [3, 2, 4, 6], index=['a', 'b', 'c', 'd'], name='sample')
s

a    3
b    2
c    4
d    6
Name: sample, dtype: int64

In [6]:
s = pd.Series(data = [3, 2, 4.0, 6], index=['a', 'b', 'c', 'd'], name='sample')
s

a    3.0
b    2.0
c    4.0
d    6.0
Name: sample, dtype: float64

In [8]:
import numpy as np

np.nan

nan

In [9]:
s = pd.Series(data = [3, np.nan, 4.0, 6], index=['a', 'b', 'c', 'd'], name='sample')
s

a    3.0
b    NaN
c    4.0
d    6.0
Name: sample, dtype: float64

In [10]:
s = pd.Series(data=[True, False, False])
s

0     True
1    False
2    False
dtype: bool

In [27]:
s = pd.Series(data=np.arange(10,20), index=pd.date_range(start='20200101', periods=10))
s

2020-01-01    10
2020-01-02    11
2020-01-03    12
2020-01-04    13
2020-01-05    14
2020-01-06    15
2020-01-07    16
2020-01-08    17
2020-01-09    18
2020-01-10    19
Freq: D, dtype: int64

In [21]:
list[s.index]

list[DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10'],
              dtype='datetime64[ns]', freq='D')]

In [24]:
s = pd.Series(data=['python', 'java', 'sql'], name='languages')
s

0    python
1      java
2       sql
Name: languages, dtype: object

In [16]:
type(s)

pandas.core.series.Series

In [22]:
s.index

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10'],
              dtype='datetime64[ns]', freq='D')

In [29]:
s.values

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [28]:
s.dtypes

dtype('int64')

In [30]:
s.shape

(10,)

In [31]:
prices = pd.Series(data={'Apple':200, 'CD Projekt':60, 'Amazon':1900, 'KGHM':np.nan})
prices

Apple          200.0
CD Projekt      60.0
Amazon        1900.0
KGHM             NaN
dtype: float64

In [34]:
prices[1]

/tmp/ipykernel_926/3717727957.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  prices[1]

np.float64(60.0)

In [35]:
prices.count()

np.int64(3)

In [44]:
prices.value_counts(dropna=False)

200.0     1
60.0      1
1900.0    1
NaN       1
Name: count, dtype: int64

In [39]:
prices.sum()

np.float64(2160.0)

In [40]:
prices.max()

1900.0

In [42]:
prices.describe()

count       3.000000
mean      720.000000
std      1024.304642
min        60.000000
25%       130.000000
50%       200.000000
75%      1050.000000
max      1900.000000
dtype: float64

In [46]:
prices.nlargest(2)

Amazon    1900.0
Apple      200.0
dtype: float64

In [48]:
prices.nsmallest(2)

CD Projekt     60.0
Apple         200.0
dtype: float64

In [49]:
prices.rank()

Apple         2.0
CD Projekt    1.0
Amazon        3.0
KGHM          NaN
dtype: float64

In [50]:
prices.sort_values()

CD Projekt      60.0
Apple          200.0
Amazon        1900.0
KGHM             NaN
dtype: float64

In [51]:
prices.sort_values(ascending=False)

Amazon        1900.0
Apple          200.0
CD Projekt      60.0
KGHM             NaN
dtype: float64

In [52]:
prices.apply(lambda x: x * 3.8)

Apple          760.0
CD Projekt     228.0
Amazon        7220.0
KGHM             NaN
dtype: float64

In [53]:
prices

Apple          200.0
CD Projekt      60.0
Amazon        1900.0
KGHM             NaN
dtype: float64

In [56]:
price_pln = prices.apply(lambda x: x*3.8)

In [59]:
price_pln

Apple          760.0
CD Projekt     228.0
Amazon        7220.0
KGHM             NaN
dtype: float64

### Dataframe

In [60]:
df = pd.DataFrame(data=[12, 12, 32])
df

    0
0  12
1  12
2  32

In [61]:
df = pd.DataFrame(data=[12, 12, 32], index=['first', 'second', 'thirs'], columns=['col_1'])
df

        col_1
first      12
second     12
thirs      32

In [62]:
df = pd.DataFrame(data={'WIG20': ['PKN ORLEN', 'PKO BP'],
                        'mWIG40': ['Amica', 'Playway']})
df

       WIG20   mWIG40
0  PKN ORLEN    Amica
1     PKO BP  Playway

In [63]:
df = pd.DataFrame(data=[[10, 12, 13], [23, 12, 10]], index=['first', 'second'], columns=['col_1', 'col_2', 'col_3'])
df

        col_1  col_2  col_3
first      10     12     13
second     23     12     10

In [64]:
df.columns

Index(['col_1', 'col_2', 'col_3'], dtype='object')

In [65]:
df.index

Index(['first', 'second'], dtype='object')

In [66]:
df.values

array([[10, 12, 13],
       [23, 12, 10]])

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, first to second
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col_1   2 non-null      int64
 1   col_2   2 non-null      int64
 2   col_3   2 non-null      int64
dtypes: int64(3)
memory usage: 172.0+ bytes

In [70]:
df.describe()

           col_1  col_2     col_3
count   2.000000    2.0   2.00000
mean   16.500000   12.0  11.50000
std     9.192388    0.0   2.12132
min    10.000000   12.0  10.00000
25%    13.250000   12.0  10.75000
50%    16.500000   12.0  11.50000
75%    19.750000   12.0  12.25000
max    23.000000   12.0  13.00000

In [72]:
df.describe().T

       count  mean       std   min    25%   50%    75%   max
col_1    2.0  16.5  9.192388  10.0  13.25  16.5  19.75  23.0
col_2    2.0  12.0  0.000000  12.0  12.00  12.0  12.00  12.0
col_3    2.0  11.5  2.121320  10.0  10.75  11.5  12.25  13.0

### Selekcja kolumn/zmiennych

In [73]:
df

        col_1  col_2  col_3
first      10     12     13
second     23     12     10

In [74]:
df['col_1']

first     10
second    23
Name: col_1, dtype: int64

In [75]:
type(df['col_1'])

pandas.core.series.Series

In [76]:
df[['col_2']]

        col_2
first      12
second     12

In [77]:
type(df[['col_2']])

pandas.core.frame.DataFrame

In [84]:
df.columns = [ 'a', 'sprzedaz_grudzien', 'c']
df

         a  sprzedaz_grudzien   c
first   10                 12  13
second  23                 12  10

In [80]:
df.a

first     10
second    23
Name: a, dtype: int64

In [85]:
df.sprzedaz_grudzien

first     12
second    12
Name: sprzedaz_grudzien, dtype: int64

In [86]:
df['d'] = df.a + df.c
df

         a  sprzedaz_grudzien   c   d
first   10                 12  13  23
second  23                 12  10  33

In [87]:
df = pd.DataFrame(data=[[10, 12, 13], [23, 12, 10]], index=['first', 'second'], columns=['col_1', 'col_2', 'col_3'])
df

        col_1  col_2  col_3
first      10     12     13
second     23     12     10

In [88]:
df.loc['first']

col_1    10
col_2    12
col_3    13
Name: first, dtype: int64

In [89]:
df.loc['second']

col_1    23
col_2    12
col_3    10
Name: second, dtype: int64

In [93]:
df.iloc[0]

col_1    10
col_2    12
col_3    13
Name: first, dtype: int64

In [94]:
df.loc['first', 'col_2']

np.int64(12)

In [95]:
df.loc[:, 'col_2']

first     12
second    12
Name: col_2, dtype: int64

In [96]:
df.iloc[0, 1]

np.int64(12)

In [97]:
df.iloc[:, 1]

first     12
second    12
Name: col_2, dtype: int64