<a href="https://colab.research.google.com/github/DGluszyk/data-science-bootcamp/blob/main/06_Uczenie_maszynowe_sklearn/02_metryki_klasyfikacja.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install plotly

Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (26.0)

In [4]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots

In [6]:
y_true = np.array([1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1])
y_pred = np.array([0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1])

In [7]:
from sklearn.metrics import accuracy_score

accuracy_score(y_true, y_pred)

0.8

In [9]:
results = pd.DataFrame({'y_true': y_true, 'y_pred': y_pred})
results

    y_true  y_pred
0        1       0
1        0       0
2        1       1
3        1       1
4        0       0
5        1       1
6        1       0
7        0       0
8        1       1
9        0       1
10       1       0
11       1       1
12       0       0
13       1       1
14       1       1
15       0       0
16       1       0
17       1       1
18       0       0
19       1       1
20       1       1
21       1       1
22       0       1
23       1       1
24       1       1
25       0       0
26       1       1
27       1       1
28       0       0
29       1       1

In [13]:
results = results.sort_values(by='y_true')
results = results.reset_index(drop=True)
results['sample'] = results.index + 1
results

    y_true  y_pred  sample
0        0       0       1
1        0       0       2
2        0       0       3
3        0       1       4
4        0       0       5
5        0       0       6
6        0       1       7
7        0       0       8
8        0       0       9
9        0       0      10
10       1       1      11
11       1       1      12
12       1       0      13
13       1       1      14
14       1       1      15
15       1       0      16
16       1       1      17
17       1       1      18
18       1       0      19
19       1       1      20
20       1       1      21
21       1       1      22
22       1       1      23
23       1       0      24
24       1       1      25
25       1       1      26
26       1       1      27
27       1       1      28
28       1       1      29
29       1       1      30

In [18]:
fig = make_subplots(rows=2, cols=1)
fig.add_trace(go.Scatter(x=results['sample'], y=results['y_true'], mode='markers', name='y_true'), row=1, col=1)
fig.add_trace(go.Scatter(x=results['sample'], y=results['y_pred'], mode='markers', name='y_pred'), row=2, col=1)
fig.update_layout(width=900, height=500, title='Klasyfikator binarny')
fig.show()

### Macierz konfuzji/pomyłek

In [30]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_true, y_pred)

In [31]:
import plotly.figure_factory as ff

def plot_confusion_matrix(cm):
    cm = cm[::-1]
    cm = pd.DataFrame(cm, columns=['pred_0', 'pred_1'], index=['true_1', 'true_0'])

    fig = ff.create_annotated_heatmap(z=cm.values, x=list(cm.columns), y=list(cm.index),
                                      colorscale='ice', showscale=True, reversescale=True)
    fig.update_layout(width=400, height=400, title='Confusion Matrix', font_size=16)
    fig.show()

In [32]:
plot_confusion_matrix(cm)

In [35]:
tn, fp, fn, tp = cm.ravel()
print(f'TN - True Negative: {tn}')
print(f'FP - False Positive: {fp}')
print(f'FN - False Negative: {fn}')
print(f'TP - True Positive: {tp}')

TN - True Negative: 8
FP - False Positive: 2
FN - False Negative: 4
TP - True Positive: 16

### Type I error - False Positive Rate


*   Element listy
*   Element listy

In [39]:
fpr = fp / (fp + tn)
fpr

np.float64(0.2)

Type II error - False Negaative Rate

In [40]:
fnr = fn / (fn + tp)
fnr

np.float64(0.2)

### Precision - ile obserwacji przewidywanych jako pozytywne są w rzeczywistości pozytywne

In [41]:
precision = tp / (tp + fp)
precision

np.float64(0.8888888888888888)

### Recall - jak wiele obserwacji z wszystkich pozytywnych sklasyfikowaliśmy jako pozytywne

In [42]:
recall = tp / (tp + fn)
recall

np.float64(0.8)

### Krzywa ROC

In [43]:
from sklearn.metrics import roc_curve

fpr, tpr, thresholds = roc_curve(y_true, y_pred, pos_label=1)
roc = pd.DataFrame({'fpr': fpr, 'tpr': tpr})
roc

   fpr  tpr
0  0.0  0.0
1  0.2  0.8
2  1.0  1.0

In [44]:
def plot_roc_curve(y_true, y_pred):
    # Binary classification
    from sklearn.metrics import roc_curve
    fpr, tpr, tresh = roc_curve(y_true, y_pred, pos_label=1)

    fig = go.Figure(data=[go.Scatter(x=roc['fpr'], y=roc['tpr'], line_color='red', name='ROC Curve'),
                        go.Scatter(x=[0, 1], y=[0, 1], mode='lines', line_dash='dash', line_color='navy')],
                    layout=go.Layout(xaxis_title='False Positive Rate',
                                    yaxis_title='True Positive Rate',
                                    title='ROC Curve',
                                    showlegend=False,
                                    width=800,
                                    height=400))
    fig.show()
plot_roc_curve(y_true, y_pred)

### Klasyfikacja wieloklasowa

In [50]:
y_true = np.array([1, 0, 1, 2, 0, 1, 1, 0, 1, 0, 1, 1, 0, 2, 1, 0, 2, 1, 0, 1, 2, 1, 2, 1, 1, 0, 1, 1, 0, 2])
y_pred = np.array([0, 0, 1, 2, 0, 1, 0, 0, 1, 1, 0, 1, 0, 2, 1, 0, 2, 1, 0, 1, 1, 1, 2, 1, 1, 0, 2, 1, 2, 2])

accuracy_score(y_true, y_pred)

0.7666666666666667

In [52]:
 cm = confusion_matrix(y_true, y_pred)
 cm

array([[ 7,  1,  1],
       [ 3, 11,  1],
       [ 0,  1,  5]])

In [53]:
def plot_confusion_matrix(cm):
    cm = cm[::-1]
    cm = pd.DataFrame(cm, columns=['pred_0', 'pred_1', 'pred_2'], index=['true_2', 'true_1', 'true_0,'])

    fig = ff.create_annotated_heatmap(z=cm.values, x=list(cm.columns), y=list(cm.index),
                                      colorscale='ice', showscale=True, reversescale=True)
    fig.update_layout(width=400, height=400, title='Confusion Matrix', font_size=16)
    fig.show()
plot_confusion_matrix(cm)

In [54]:
from sklearn.metrics import classification_report

print(classification_report(y_true, y_pred))

              precision    recall  f1-score   support

           0       0.70      0.78      0.74         9
           1       0.85      0.73      0.79        15
           2       0.71      0.83      0.77         6

    accuracy                           0.77        30
   macro avg       0.75      0.78      0.76        30
weighted avg       0.78      0.77      0.77        30

In [55]:
print(classification_report(y_true, y_pred, target_names=['label_1', 'label_2', 'label_3']))

              precision    recall  f1-score   support

     label_1       0.70      0.78      0.74         9
     label_2       0.85      0.73      0.79        15
     label_3       0.71      0.83      0.77         6

    accuracy                           0.77        30
   macro avg       0.75      0.78      0.76        30
weighted avg       0.78      0.77      0.77        30